java.target=${ant.java.version}
java.args=

src.dir=src

backend.src.full.dir=${src.dir}/main
backend.src.java.dir=${backend.src.full.dir}/java
backend.src.resource.dir=${backend.src.full.dir}/resources
backend.libs.dir=libs
native2ascii.resources.dir=${backend.src.resource.dir}/native2ascii

frontend.src.dir=${src.dir}/webapp

build.dir=build
build.classes.dir=${build.dir}/classes

test.backend.src.dir=${src.dir}/test/java
test.build.classes.dir=${build.dir}/test/classes

report.dir=${build.dir}/report

assets.dir=assets
assets.sound.dir=${assets.dir}/sound

docs.dir=docs
docs.java.dir=${docs.dir}/javadoc

commit.forbidden.list.file=.forbidden
commit.msg=feat: auto commit changes

alt.dir=alt
alt.backend.src.full.dir=${alt.dir}/src
alt.backend.src.java.dir=${alt.backend.src.full.dir}/java