src.dir=src
backend.src.dir=${src.dir}/main/java
frontend.src.dir==${src.dir}/webapp
backend.libs.dir=libs

build.dir=build
build.classes.dir=${build.dir}/classes

test.backend.src.dir=${src.dir}/test/java
test.build.classes.dir=${build.dir}/test/classes