java.target=${ant.java.version}
java.args=

src.dir=src
backend.src.dir=${src.dir}
backend.src.java.dir=${src.dir}/main/java
backend.src.resource.dir=${src.dir}/main/resources
native2ascii.resources.dir=${backend.src.resource.dir}/native2ascii
frontend.src.dir=${src.dir}/webapp
backend.libs.dir=libs

build.dir=build
build.classes.dir=${build.dir}/classes
destination-name=webapp

test.backend.src.dir=${src.dir}/test/java
test.build.classes.dir=${build.dir}/test/classes

report.dir=${build.dir}/report

assets.dir=assets
assets.sound.dir=${assets.dir}/sound
